# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'SonarQube-Server'
    scannerMode: 'other'
- task: Maven@4
  inputs:
    azureSubscription: 'Azure subscription 1(1)(0894542e-f1c7-495e-a954-85424a27e7ef)'
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'

- task: SonarQubeAnalyze@8
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'