trigger:
- main

pool:
  name: 'PersonalAgentMachine'

stages:
- stage: Build_Test_Analyze
  displayName: Build Test Analyze
  jobs:
  - job: MavenAndSonar
    displayName: Maven Build and SonarQube
    steps:
    - checkout: self

    - task: JavaToolInstaller@0
      displayName: Install Java 17
      inputs:
        versionSpec: '17'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: SonarQubePrepare@8
      displayName: Prepare SonarQube
      inputs:
        SonarQube: 'SonarQube-Server'
        scannerMode: 'other'

    - task: Maven@4
      displayName: Maven Build
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'

    - task: SonarQubeAnalyze@8
      displayName: Run SonarQube Analysis
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@8
      displayName: Publish Quality Gate
      inputs:
        pollingTimeoutSec: '300'